version: "3"
services:
  db:
    image: mariadb:10.3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booq
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - '3306'
    ports:
      - '3306:3306'

  booq-server:
    build: .
    environment:
      BOOQ_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: booq
    volumes:
      - './:/go/src/github.com/traPtitech/booQ'
    tty: true
    entrypoint: dockerize -timeout 60s -wait tcp://db:3306
    command: fresh -c fresh.conf
    ports:
      - '8080:3001'
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/swagger.yml:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "4000:8080"
